apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmmgr
  namespace: study
  labels:
    app: helmmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmmgr
  template:
    metadata:
      labels:
        app: helmmgr
    spec:
      containers:
        - name: helmmgr
          image: registry.cn-shanghai.aliyuncs.com/digk8s/helmmgr:v1.0.0
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "100Mi"
              cpu: "165m"
              ephemeral-storage: "200Mi"
          imagePullPolicy: Always
